# Generated by Django 6.1 on 2026-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "主板"),
                            ("gpu", "显卡"),
                            ("memory", "内存"),
                            ("storage", "存储"),
                            ("power", "电源"),
                            ("cooler", "散热器"),
                            ("case", "机箱"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="型号/名称")),
                (
                    "attributes",
                    models.JSONField(blank=True, default=dict, verbose_name="兼容属性"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "硬件型号",
                "verbose_name_plural": "硬件型号",
                "ordering": ["category", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"),
                        name="unique_component_category_name",
                    )
                ],
            },
        ),
    ]
